In [1]:
import pandas as pd
ruta="https://github.com/Enrique867/PC2/raw/refs/heads/main/HDI.xlsx"
data = pd.read_excel(ruta, engine='openpyxl', dtype=str,keep_default_na=False)

In [2]:
print(data.shape)
data.head()

(276, 15)

,Back,Table 1. Human Development Index and its components,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,,,,,,,,,,,,,,,
1,,,,,SDG3,,SDG4.3,,SDG4.4,,SDG8.5,,,,
2,,,,,,,,,,,,,,,
3,,,Human Development Index (HDI),,Life expectancy at birth,,Expected years of schooling,,Mean years of schooling,,Gross national income (GNI) per capita,,GNI per capita rank minus HDI rank,,HDI rank
4,HDI rank,Country,Value,,(years),,(years),,(years),,(2017 PPP $),,,,

In [3]:
columnas_a_eliminar = ['Unnamed: 3', 'Unnamed: 5', 'Unnamed: 7', 'Unnamed: 9', 'Unnamed: 11', 'Unnamed: 13']


data = data.drop(columns=columnas_a_eliminar, errors='ignore')


print(data.shape)
data.head()

(276, 9)

,Back,Table 1. Human Development Index and its components,Unnamed: 2,Unnamed: 4,Unnamed: 6,Unnamed: 8,Unnamed: 10,Unnamed: 12,Unnamed: 14
0,,,,,,,,,
1,,,,SDG3,SDG4.3,SDG4.4,SDG8.5,,
2,,,,,,,,,
3,,,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank
4,HDI rank,Country,Value,(years),(years),(years),(2017 PPP $),,

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 276 entries, 0 to 275
Data columns (total 9 columns):
 #   Column                                                Non-Null Count  Dtype
---  ------                                                --------------  -----
 0   Back                                                  276 non-null    object
 1   Table 1. Human Development Index and its components   276 non-null    object
 2   Unnamed: 2                                            276 non-null    object
 3   Unnamed: 4                                            276 non-null    object
 4   Unnamed: 6                                            276 non-null    object
 5   Unnamed: 8                                            276 non-null    object
 6   Unnamed: 10                                           276 non-null    object
 7   Unnamed: 12                                           276 non-null    object
 8   Unnamed: 14                                           276 non-null    object
dtypes: object(9)
memory usage: 19.5+ KB

In [5]:
import re
start_row = 7
start_col = 3

def extraer_numero_con_signo(texto):
    if isinstance(texto, str):
        match = re.search(r'^[+-]?\d+(\.\d+)?', texto)
        return match.group(0) if match else None
    return None

for col in data.columns[start_col:]:
    data.loc[start_row:, col] = data.loc[start_row:, col].apply(extraer_numero_con_signo)


print(data.iloc[6:, 2:])

    Unnamed: 2 Unnamed: 4   Unnamed: 6   Unnamed: 8  Unnamed: 10 Unnamed: 12  \
6
7        0.962    83.9872  16.50029945  13.85966015  66933.00454           5
8        0.961    83.2339  18.18519974  13.00362968  64660.10622           6
9        0.959    82.6782  19.16305923  13.76716995  55782.04981          11
10       0.952    85.4734  17.27816963  12.22620964   62606.8454           6
..         ...        ...          ...          ...          ...         ...
271                  None         None         None         None        None
272                  None         None         None         None        None
273                  None         None         None         None        None
274                  None         None         None         None        None
275                  None         None         None         None        None

    Unnamed: 14
6
7             3
8             1
9             2
10            4
..          ...
271        None
272        None
273        None
274        None
275        None

[270 rows x 7 columns]

In [6]:
start_row = 7
start_col = 3


for col_idx in range(start_col, len(data.columns)):
    col_name = data.columns[col_idx]
    data.loc[start_row:, col_name] = pd.to_numeric(data.loc[start_row:, col_name], errors='coerce')


print(data.shape)
data.head(15)

(276, 9)

,Back,Table 1. Human Development Index and its components,Unnamed: 2,Unnamed: 4,Unnamed: 6,Unnamed: 8,Unnamed: 10,Unnamed: 12,Unnamed: 14
0,,,,,,,,,
1,,,,SDG3,SDG4.3,SDG4.4,SDG8.5,,
2,,,,,,,,,
3,,,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank
4,HDI rank,Country,Value,(years),(years),(years),(2017 PPP $),,
5,,,2021,2021,2021,2021,2021,2021,2020
6,,VERY HIGH HUMAN DEVELOPMENT,,,,,,,
7,1,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454,5.0,3.0
8,2,Norway,0.961,83.2339,18.1852,13.00363,64660.10622,6.0,1.0
9,3,Iceland,0.959,82.6782,19.163059,13.76717,55782.04981,11.0,2.0
10,4,"Hong Kong, China (SAR)",0.952,85.4734,17.27817,12.22621,62606.8454,6.0,4.0
11,5,Australia,0.951,84.5265,21.05459,12.72682,49238.43335,18.0,5.0
12,6,Denmark,0.948,81.3753,18.7148,12.96049,60364.78595,6.0,5.0
13,7,Sweden,0.947,82.9833,19.41853,12.60972,54489.37401,9.0,9.0
14,8,Ireland,0.945,81.9976,18.945221,11.582223,76168.98443,-3.0,8.0

In [7]:
nuevos_nombres = {
    data.columns[2]: 'HDI_Value',
    data.columns[3]: 'Life_Expectancy_at_Birth',
    data.columns[4]: 'Expected_Years_of_Schooling',
    data.columns[5]: 'Mean_Years_of_Schooling',
    data.columns[6]: 'GNI_per_Capita',
    data.columns[7]: 'GNI_Rank_Minus_HDI_Rank',
    data.columns[8]: 'HDI_Rank'
}

data = data.rename(columns=nuevos_nombres)


# Para verificar el resultado (opcional)
print(data.shape)
data.head(15)

(276, 9)

,Back,Table 1. Human Development Index and its components,HDI_Value,Life_Expectancy_at_Birth,Expected_Years_of_Schooling,Mean_Years_of_Schooling,GNI_per_Capita,GNI_Rank_Minus_HDI_Rank,HDI_Rank
0,,,,,,,,,
1,,,,SDG3,SDG4.3,SDG4.4,SDG8.5,,
2,,,,,,,,,
3,,,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank
4,HDI rank,Country,Value,(years),(years),(years),(2017 PPP $),,
5,,,2021,2021,2021,2021,2021,2021,2020
6,,VERY HIGH HUMAN DEVELOPMENT,,,,,,,
7,1,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454,5.0,3.0
8,2,Norway,0.961,83.2339,18.1852,13.00363,64660.10622,6.0,1.0
9,3,Iceland,0.959,82.6782,19.163059,13.76717,55782.04981,11.0,2.0
10,4,"Hong Kong, China (SAR)",0.952,85.4734,17.27817,12.22621,62606.8454,6.0,4.0
11,5,Australia,0.951,84.5265,21.05459,12.72682,49238.43335,18.0,5.0
12,6,Denmark,0.948,81.3753,18.7148,12.96049,60364.78595,6.0,5.0
13,7,Sweden,0.947,82.9833,19.41853,12.60972,54489.37401,9.0,9.0
14,8,Ireland,0.945,81.9976,18.945221,11.582223,76168.98443,-3.0,8.0

In [8]:
data = data.iloc[7:]

data = data.reset_index(drop=True)

print(data.shape)
data.head(15)

(269, 9)

,Back,Table 1. Human Development Index and its components,HDI_Value,Life_Expectancy_at_Birth,Expected_Years_of_Schooling,Mean_Years_of_Schooling,GNI_per_Capita,GNI_Rank_Minus_HDI_Rank,HDI_Rank
0,1,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454,5.0,3.0
1,2,Norway,0.961,83.2339,18.1852,13.00363,64660.10622,6.0,1.0
2,3,Iceland,0.959,82.6782,19.163059,13.76717,55782.04981,11.0,2.0
3,4,"Hong Kong, China (SAR)",0.952,85.4734,17.27817,12.22621,62606.8454,6.0,4.0
4,5,Australia,0.951,84.5265,21.05459,12.72682,49238.43335,18.0,5.0
5,6,Denmark,0.948,81.3753,18.7148,12.96049,60364.78595,6.0,5.0
6,7,Sweden,0.947,82.9833,19.41853,12.60972,54489.37401,9.0,9.0
7,8,Ireland,0.945,81.9976,18.945221,11.582223,76168.98443,-3.0,8.0
8,9,Germany,0.942,80.6301,17.010139,14.090967,54534.21682,6.0,7.0
9,10,Netherlands,0.941,81.6873,18.693165,12.58163,55979.411,3.0,10.0
10,11,Finland,0.94,82.0381,19.051929,12.87362,49452.16672,11.0,12.0
11,12,Singapore,0.939,82.7545,16.524321,11.92488,90918.64471,-10.0,10.0
12,13,Belgium,0.937,81.8787,19.604219,12.37568,52293.39977,7.0,16.0
13,13,New Zealand,0.937,82.4513,20.28389,12.94469,44057.31394,16.0,13.0
14,15,Canada,0.936,82.6565,16.396259,13.834427,46807.98619,9.0,15.0

In [9]:
data = data.iloc[:, 1:]
data = data.reset_index(drop=True)
print(data.shape)
data.head(230)

(269, 8)

,Table 1. Human Development Index and its components,HDI_Value,Life_Expectancy_at_Birth,Expected_Years_of_Schooling,Mean_Years_of_Schooling,GNI_per_Capita,GNI_Rank_Minus_HDI_Rank,HDI_Rank
0,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454,5.0,3.0
1,Norway,0.961,83.2339,18.1852,13.00363,64660.10622,6.0,1.0
2,Iceland,0.959,82.6782,19.163059,13.76717,55782.04981,11.0,2.0
3,"Hong Kong, China (SAR)",0.952,85.4734,17.27817,12.22621,62606.8454,6.0,4.0
4,Australia,0.951,84.5265,21.05459,12.72682,49238.43335,18.0,5.0
...,...,...,...,...,...,...,...,...
225,b. Based on countries for which a Human Develo...,,NaN,NaN,NaN,NaN,NaN,NaN
226,"c. In calculating the HDI value, expected year...",,NaN,NaN,NaN,NaN,NaN,NaN
227,"d. In calculating the HDI value, life expectan...",,NaN,NaN,NaN,NaN,NaN,NaN
228,e. Updated by HDRO based on data from UNESCO I...,,NaN,NaN,NaN,NaN,NaN,NaN
229,"f. In calculating the HDI value, GNI per capit...",,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
print(data.shape)
data.head(228)

(269, 8)

,Table 1. Human Development Index and its components,HDI_Value,Life_Expectancy_at_Birth,Expected_Years_of_Schooling,Mean_Years_of_Schooling,GNI_per_Capita,GNI_Rank_Minus_HDI_Rank,HDI_Rank
0,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454,5.0,3.0
1,Norway,0.961,83.2339,18.1852,13.00363,64660.10622,6.0,1.0
2,Iceland,0.959,82.6782,19.163059,13.76717,55782.04981,11.0,2.0
3,"Hong Kong, China (SAR)",0.952,85.4734,17.27817,12.22621,62606.8454,6.0,4.0
4,Australia,0.951,84.5265,21.05459,12.72682,49238.43335,18.0,5.0
...,...,...,...,...,...,...,...,...
223,Notes,,NaN,NaN,NaN,NaN,NaN,NaN
224,a. Data refer to 2021 or the most recent year ...,,NaN,NaN,NaN,NaN,NaN,NaN
225,b. Based on countries for which a Human Develo...,,NaN,NaN,NaN,NaN,NaN,NaN
226,"c. In calculating the HDI value, expected year...",,NaN,NaN,NaN,NaN,NaN,NaN
227,"d. In calculating the HDI value, life expectan...",,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
data = data.iloc[:194]
data = data.reset_index(drop=True)
print(data.shape)
data.head(194)

(194, 8)

,Table 1. Human Development Index and its components,HDI_Value,Life_Expectancy_at_Birth,Expected_Years_of_Schooling,Mean_Years_of_Schooling,GNI_per_Capita,GNI_Rank_Minus_HDI_Rank,HDI_Rank
0,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454,5.0,3.0
1,Norway,0.961,83.2339,18.1852,13.00363,64660.10622,6.0,1.0
2,Iceland,0.959,82.6782,19.163059,13.76717,55782.04981,11.0,2.0
3,"Hong Kong, China (SAR)",0.952,85.4734,17.27817,12.22621,62606.8454,6.0,4.0
4,Australia,0.951,84.5265,21.05459,12.72682,49238.43335,18.0,5.0
...,...,...,...,...,...,...,...,...
189,Burundi,0.426,61.6627,10.722722,3.129267,731.786709,4.0,187.0
190,Central African Republic,0.404,53.8947,8.040172,4.334,966.058611,1.0,188.0
191,Niger,0.4,61.5763,6.957112,2.116717,1239.866936,-3.0,189.0
192,Chad,0.394,52.5254,8.035914,2.573774,1364.169417,-7.0,190.0
193,South Sudan,0.385,54.9752,5.54251,5.72614,767.787,-1.0,191.0

In [21]:
data.rename(columns={"Table 1. Human Development Index and its components ": "Country"}, inplace=True)
print(data.shape)
data.head(194)

(194, 8)

,Country,HDI_Value,Life_Expectancy_at_Birth,Expected_Years_of_Schooling,Mean_Years_of_Schooling,GNI_per_Capita,GNI_Rank_Minus_HDI_Rank,HDI_Rank
0,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454,5.0,3.0
1,Norway,0.961,83.2339,18.1852,13.00363,64660.10622,6.0,1.0
2,Iceland,0.959,82.6782,19.163059,13.76717,55782.04981,11.0,2.0
3,"Hong Kong, China (SAR)",0.952,85.4734,17.27817,12.22621,62606.8454,6.0,4.0
4,Australia,0.951,84.5265,21.05459,12.72682,49238.43335,18.0,5.0
...,...,...,...,...,...,...,...,...
189,Burundi,0.426,61.6627,10.722722,3.129267,731.786709,4.0,187.0
190,Central African Republic,0.404,53.8947,8.040172,4.334,966.058611,1.0,188.0
191,Niger,0.4,61.5763,6.957112,2.116717,1239.866936,-3.0,189.0
192,Chad,0.394,52.5254,8.035914,2.573774,1364.169417,-7.0,190.0
193,South Sudan,0.385,54.9752,5.54251,5.72614,767.787,-1.0,191.0

In [30]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Country                      194 non-null    object
 1   HDI_Value                    194 non-null    object
 2   Life_Expectancy_at_Birth     191 non-null    object
 3   Expected_Years_of_Schooling  191 non-null    object
 4   Mean_Years_of_Schooling      191 non-null    object
 5   GNI_per_Capita               191 non-null    object
 6   GNI_Rank_Minus_HDI_Rank      191 non-null    object
 7   HDI_Rank                     191 non-null    object
dtypes: object(8)
memory usage: 12.3+ KB

In [36]:
data['HDI_Value'] = pd.to_numeric(data['HDI_Value'], errors='coerce')
data['Life_Expectancy_at_Birth'] = pd.to_numeric(data['Life_Expectancy_at_Birth'], errors='coerce')
data['Expected_Years_of_Schooling'] = pd.to_numeric(data['Expected_Years_of_Schooling'], errors='coerce')
data['Mean_Years_of_Schooling'] = pd.to_numeric(data['Mean_Years_of_Schooling'], errors='coerce')
data['GNI_per_Capita'] = pd.to_numeric(data['GNI_per_Capita'], errors='coerce')

In [37]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Country                      194 non-null    object
 1   HDI_Value                    191 non-null    float64
 2   Life_Expectancy_at_Birth     191 non-null    float64
 3   Expected_Years_of_Schooling  191 non-null    float64
 4   Mean_Years_of_Schooling      191 non-null    float64
 5   GNI_per_Capita               191 non-null    float64
 6   GNI_Rank_Minus_HDI_Rank      191 non-null    object
 7   HDI_Rank                     191 non-null    object
dtypes: float64(5), object(3)
memory usage: 12.3+ KB

In [38]:
print(data.shape)
data.head(68)

(194, 8)

,Country,HDI_Value,Life_Expectancy_at_Birth,Expected_Years_of_Schooling,Mean_Years_of_Schooling,GNI_per_Capita,GNI_Rank_Minus_HDI_Rank,HDI_Rank
0,Switzerland,0.962,83.9872,16.500299,13.859660,66933.00454,5.0,3.0
1,Norway,0.961,83.2339,18.185200,13.003630,64660.10622,6.0,1.0
2,Iceland,0.959,82.6782,19.163059,13.767170,55782.04981,11.0,2.0
3,"Hong Kong, China (SAR)",0.952,85.4734,17.278170,12.226210,62606.84540,6.0,4.0
4,Australia,0.951,84.5265,21.054590,12.726820,49238.43335,18.0,5.0
...,...,...,...,...,...,...,...,...
63,Mauritius,0.802,73.5552,15.173530,10.427910,22025.34631,-1.0,62.0
64,Serbia,0.802,74.1923,14.400090,11.369870,19123.02747,4.0,62.0
65,Thailand,0.800,78.7154,15.882219,8.697120,17030.15352,6.0,64.0
66,HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,Albania,0.796,76.4626,14.448000,11.286455,14131.11039,17.0,68.0

In [46]:
data = data.drop(161)

In [49]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 191 entries, 0 to 193
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Country                      191 non-null    object
 1   HDI_Value                    191 non-null    float64
 2   Life_Expectancy_at_Birth     191 non-null    float64
 3   Expected_Years_of_Schooling  191 non-null    float64
 4   Mean_Years_of_Schooling      191 non-null    float64
 5   GNI_per_Capita               191 non-null    float64
 6   GNI_Rank_Minus_HDI_Rank      191 non-null    object
 7   HDI_Rank                     191 non-null    object
dtypes: float64(5), object(3)
memory usage: 17.5+ KB